name: Baylee's Blog
description: >-
  Helping organize my thoughts since 2021 🦄
author-bio: >-
  Having thoughts to organize since 1990 🦄
author: Baylee (they/them/theirs)
baseurl: "/blog"
url: "https://baylee.dev"
github:  bayleedev
instagram: princess.wiggles
markdown: kramdown
permalink: pretty
plugins:
    - jekyll-paginate
    - jekyll-feed
paginate: 10
paginate_path: "/page/:num"
sass:
  sass_dir: _scss
  style: :compressed
